import './style.css';
import {MagazineAudioPlayer,GlobalMiniPlayer} from './player/audio-component';
import {audioService} from './player/audio-service';
import {ShuffleBag} from './shuffle.mjs';
customElements.define('m-audio-player',MagazineAudioPlayer);customElements.define('m-global-mini-player',GlobalMiniPlayer);
interface Media{src:string;title:string;type:'audio'|'video'}
const status=document.querySelector('#media-error')!;
const poster='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"><defs><radialGradient id="g"><stop stop-color="#626c35"/><stop offset="1" stop-color="#12140e"/></radialGradient></defs><path fill="url(#g)" d="M0 0h1600v900H0z"/></svg>');
function selectTrack(track:Media){const slot=document.querySelector('#player-slot')!;slot.replaceChildren();const player=document.createElement('m-audio-player');for(const [key,value] of Object.entries({src:track.src,title:track.title,artist:'Doom Kitty',bg:poster}))player.setAttribute(key,value);if(track.type==='video')player.setAttribute('video-src',track.src);slot.append(player);audioService.play(track.src,track.title,'Doom Kitty').catch(()=>{status.textContent='Press play to start listening.';});slot.scrollIntoView({behavior:'smooth',block:'center'});}
audioService.on('error',()=>{status.textContent='This media could not be played. Try another track.';});audioService.on('play',()=>{status.textContent='';});
function empty(target:string,title:string,detail:string){const box=document.createElement('div');box.className='empty-state';const heading=document.createElement('strong');heading.textContent=title;const copy=document.createElement('span');copy.textContent=detail;box.append(heading,copy);document.querySelector(target)!.append(box);}
class OpeningFilms{
private videos=Array.from(document.querySelectorAll<HTMLVideoElement>('.video-stage video'));private bag:ShuffleBag;private active=0;private prepared=false;private switching=false;private paused=matchMedia('(prefers-reduced-motion: reduce)').matches;private failed=new Set<string>();
constructor(clips:Media[]){this.bag=new ShuffleBag(clips.map(c=>c.src));const button=document.querySelector<HTMLButtonElement>('#motion')!;button.addEventListener('click',()=>{this.paused=!this.paused;this.updateButton();if(this.paused)this.videos.forEach(v=>v.pause());else this.videos[this.active].play().catch(()=>{this.paused=true;this.updateButton();});});this.updateButton();if(!clips.length){document.querySelector<HTMLElement>('.empty-note')!.hidden=false;button.hidden=true;return;}const first=this.videos[0];first.src=this.bag.next()!;first.loop=clips.length===1;first.classList.add('active');if(!this.paused)first.play().catch(()=>{this.paused=true;this.updateButton();});if(clips.length>1){this.prepare();for(const video of this.videos){video.addEventListener('timeupdate',()=>{if(video===this.videos[this.active]&&Number.isFinite(video.duration)&&video.duration-video.currentTime<.85)void this.advance();});video.addEventListener('ended',()=>{if(video===this.videos[this.active])void this.advance();});video.addEventListener('error',()=>{this.failed.add(video.getAttribute('src')||'');if(this.failed.size>=clips.length){document.querySelector('#film-status')!.textContent='Opening films unavailable';return;}if(video===this.videos[this.active])void this.advance();else this.prepare();});}}}
private updateButton(){const button=document.querySelector<HTMLButtonElement>('#motion')!;button.textContent=this.paused?'Play visuals ▷':'Pause visuals Ⅱ';button.setAttribute('aria-pressed',String(this.paused));}
private prepare(){const next=this.videos[1-this.active];this.prepared=false;let src=this.bag.next();for(let i=0;i<this.failed.size&&src&&this.failed.has(src);i++)src=this.bag.next();if(!src||this.failed.has(src))return;next.src=src;next.load();const ready=()=>{this.prepared=true;if(this.videos[this.active].ended)void this.advance();};if(next.readyState>=2)ready();else next.addEventListener('loadeddata',ready,{once:true});}
private async advance(){if(this.switching||!this.prepared||this.paused)return;this.switching=true;const old=this.videos[this.active],next=this.videos[1-this.active];try{next.currentTime=0;await next.play();if(this.paused){next.pause();return;}next.classList.add('active');old.classList.remove('active');await new Promise(resolve=>setTimeout(resolve,750));old.pause();this.active=1-this.active;this.prepare();}catch{this.paused=true;this.updateButton();}finally{this.switching=false;}}
}
async function init(){try{const response=await fetch('./media-manifest.json');if(!response.ok)throw Error('Manifest unavailable');const media:Media[]=await response.json(),clips=media.filter(m=>m.type==='video'),music=media.filter(m=>m.type==='audio'),tracks=music.length?music:clips;new OpeningFilms(clips);if(!tracks.length)empty('#track-list','The first release is coming.','This space is ready for Doom Kitty’s music.');tracks.forEach((track,index)=>{const button=document.createElement('button');button.className='track-row';const number=document.createElement('span');number.className='number';number.textContent=String(index+1).padStart(2,'0');const name=document.createElement('strong');name.textContent=track.title;const type=document.createElement('small');type.textContent=track.type==='audio'?'Audio / Doom Kitty':'Film / Doom Kitty';const play=document.createElement('span');play.textContent='Play ↗';button.append(number,name,type,play);button.addEventListener('click',()=>selectTrack(track));document.querySelector('#track-list')!.append(button);});if(!clips.length)empty('#film-grid','A world in motion.','The opening films will appear here when they arrive.');clips.forEach(clip=>{const button=document.createElement('button');button.className='film-card';const preview=document.createElement('video');preview.src=clip.src;preview.muted=true;preview.playsInline=true;preview.preload='metadata';const label=document.createElement('span');label.textContent=clip.title+' ↗';button.append(preview,label);button.addEventListener('click',()=>selectTrack(clip));document.querySelector('#film-grid')!.append(button);});}catch{empty('#track-list','Music is on its way.','Please try again shortly.');empty('#film-grid','Films are on their way.','Please try again shortly.');new OpeningFilms([]);}}void init();
